# Generated by Django 3.1.5 on 2021-05-06 16:01

import accounts.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.TextField()),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_artist', models.BooleanField(default=False)),
                ('is_demix_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('bio', models.TextField(blank=True, null=True)),
                ('custom_url', models.CharField(max_length=255, unique=True)),
                ('aadhar_card_no', models.TextField(blank=True, null=True)),
                ('pan_card_no', models.TextField(blank=True, null=True)),
                ('gst_no', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(default='uploads/profile_pictures/default.png', null=True, upload_to=accounts.models.image_directory_path, verbose_name='profile picture')),
                ('cashout_requested', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ifsc_code', models.TextField(blank=True, null=True)),
                ('account_number', models.TextField(blank=True, null=True)),
                ('bank_branch', models.TextField(blank=True, null=True)),
                ('beneficiary_name', models.TextField(blank=True, null=True)),
                ('upi_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('profile_picture', models.ImageField(default='uploads/profile_pictures/default.png', null=True, upload_to=accounts.models.image_directory_path, verbose_name='profile picture')),
            ],
        ),
        migrations.CreateModel(
            name='DemixAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('a_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Pickup', 'Pickup')], max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
