# Generated by Django 3.1.5 on 2021-05-25 17:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_artist_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_picture',
            field=models.ImageField(default='uploads/cover_pictures/default.png', null=True, upload_to=accounts.models.cover_image_directory_path, verbose_name='cover picture'),
        ),
    ]
