# Generated by Django 3.1.5 on 2021-05-25 18:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210525_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cover_picture',
            field=models.ImageField(default='users/cover_pictures/default.jpg', null=True, upload_to=accounts.models.cover_image_directory_path, verbose_name='cover picture'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(default='users/profile_pictures/default.jpg', null=True, upload_to=accounts.models.image_directory_path, verbose_name='profile picture'),
        ),
    ]
